# Shows the "Sponsor" button on the GitHub project page.
buy_me_a_coffee: captainibo
custom:
  - "https://buymeacoffee.com/captainibo"
  - "https://buffer.com/join/bf6b3aee5bee700fe35c863ee82aad7f70eb1955367e27c92247144b95ea8af5"
